### ISSUE TITLE
unpkg vs rollup: pros and cons

### ISSUE THREAD

**Issue by ghost** [LinkPact/Self-actualization-webapp-frontend#1]
# [unpkg](https://unpkg.com)
## Pros
- Allows us to remove build step
- Since it is a CDN backed by Cloudflare it may allow assets to load faster if the user is further from our server on AWS
- Can automatically update dependencies to prevent vulnerabilities

## Cons
- May break site if a dependency is updated. (**solution: Use fixed version**)
- May cause problems with CORS
- Outages
- May cost money in the future

# [rollup](https://rollupjs.org)
## Pros
- We might need a build step for other tasks (minifying, transpiling to use experimental javascript features, etc.)
- Dependencies are loaded faster for local development
- Might be easier to handle CORS when all assets are loaded from same domain

## Cons
- Requires build steps
- Requires manual updating of dependencies

I suggest using **unpkg**, mainly because it allows us to remove the build process.

**Comment by Jakob37** [comment]
Hi! I missed this. Yes, it seems to make sense to start with unpkg. It seems like it would be OK to switch approach at a later point if needed.
